//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class consept
    {
        public int NumeroIdentificacion { get; set; }
        public Nullable<int> TipoDocumento { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
