//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crudmvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class dato
    {
        public int Id { get; set; }
        public string Datos { get; set; }
    }
}
